# Basic Python

## 1. Split this string

In [ ]:
s = "Hi there Sam!"
words = s.split(' ')
print(words)

['Hi', 'there', 'Sam!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
planet = "Earth"
diameter = 12742
txt = "The diameter of {planet} is {diameter} kilometers.".format(planet = "Earth",diameter = 12742)
print(txt)

The diameter of Earth is 12742 kilometers.


## 3. In this nest dictionary grab the word "hello"

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}


In [ ]:
d1=d['k1'][3]


d2= d1['tricky'][3]

In [ ]:
d2= d1['tricky'][3]


In [ ]:
d2['target'][3]


'hello'

# Numpy

In [ ]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [ ]:
arr=np.zeros(10)

In [ ]:
arr1=np.ones(10)*5

In [ ]:
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
print(arr1)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [ ]:
arreven=np.arange(20,35,2)

In [ ]:
print(arreven)

[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
matrix=np.arange(0,9).reshape(3,3)

In [ ]:
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatinate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])
concat=np.concatenate((a,b),axis=0)

In [ ]:
print(concat)

[1 2 3 4 5 6]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [ ]:
import pandas as pd


In [ ]:
lists = {
    "a":["1","10"],
    "b":["2","20"],
    "c":["3","30"]
         }

In [ ]:
pd.DataFrame(lists)

a   b   c
0   1   2   3
1  10  20  30

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [ ]:
from datetime import date
start_date = date(2023,1,1)
end_date = date(2023,2,11)
[date.fromordinal(i) for i in range(start_date.toordinal(), end_date.toordinal())]

[datetime.date(2023, 1, 1),
 datetime.date(2023, 1, 2),
 datetime.date(2023, 1, 3),
 datetime.date(2023, 1, 4),
 datetime.date(2023, 1, 5),
 datetime.date(2023, 1, 6),
 datetime.date(2023, 1, 7),
 datetime.date(2023, 1, 8),
 datetime.date(2023, 1, 9),
 datetime.date(2023, 1, 10),
 datetime.date(2023, 1, 11),
 datetime.date(2023, 1, 12),
 datetime.date(2023, 1, 13),
 datetime.date(2023, 1, 14),
 datetime.date(2023, 1, 15),
 datetime.date(2023, 1, 16),
 datetime.date(2023, 1, 17),
 datetime.date(2023, 1, 18),
 datetime.date(2023, 1, 19),
 datetime.date(2023, 1, 20),
 datetime.date(2023, 1, 21),
 datetime.date(2023, 1, 22),
 datetime.date(2023, 1, 23),
 datetime.date(2023, 1, 24),
 datetime.date(2023, 1, 25),
 datetime.date(2023, 1, 26),
 datetime.date(2023, 1, 27),
 datetime.date(2023, 1, 28),
 datetime.date(2023, 1, 29),
 datetime.date(2023, 1, 30),
 datetime.date(2023, 1, 31),
 datetime.date(2023, 2, 1),
 datetime.date(2023, 2, 2),
 datetime.date(2023, 2, 3),
 datetime.date(2023, 2, 4)

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [ ]:
df = pd.DataFrame(lists,columns = ['Sno','Name','Age'])
print(df)

   Sno Name  Age
0    1  aaa   22
1    2  bbb   25
2    3  ccc   24
